#!/usr/bin/env bash
# nginx

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sed -i '/listen 80 Default_server/i add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
