#!/usr/bin/env bash
# Installs a proxy on a new load balancer and sets up the config.

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.*
sudo service haproxy start

echo "frontend haproxynode
        bind *:80
        mode http
        default_backend backendnodes
backend backendnodes
        balance roundrobin
        server web-01 3.89.155.155:80 check
        server web-02 34.202.159.191:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
